### ISSUE TITLE
data presentation standards

### ISSUE THREAD

**Issue by ligongus** [jhs-hwg/nhanesShinyBP#11]
I tried to update more files for data presentation standards, but got the following message when git push was used:
$ git push
remote: Permission to jhs-hwg/nhanesShinyBP.git denied to ligongus.
fatal: unable to access 'https://github.com/jhs-hwg/nhanesShinyBP.git/': The requested URL returned error: 403

**Comment by ligongus** [comment]
Should I do the following:
git push https://github.com/jhs-hwg/nhanesShinyBP.git/ master
git request-pull ligongus https://github.com/jhs-hwg/nhanesShinyBP.git/ master

**Comment by ligongus** [comment]
I was able to create a pull request to add "get_psu_count" and "get_strata_count" functions. I did not click "merge pull request" though. If I remember correctly, "merge pull request" should be done by the lead. Another issue: I do not see my newly created files such as "get_obs_count" in my branch though.

**Comment by bcjaeger** [comment]
That makes sense! I did not create `get_obs_count` so it should not be in there yet. I will check out the pull request now.

**Comment by bcjaeger** [comment]
I actually don't see a pull request. Maybe we could have a quick chat tomorrow to review your steps? I have to be out of the house for a bit in the afternoon but I should be free around 1pm central time

**Comment by bcjaeger** [comment]
I found the pull request! Unfortunately, it looks like the pull request was submitted to your forked repo and not to this repo. We can fix this tomorrow if you have time to chat.

**Comment by ligongus** [comment]
OK. I will be available any time Friday.

**Comment by bcjaeger** [comment]
Closing this issue as we completed this discussion. I still need to work on incorporating Ligong's svyprop functions.
