### ISSUE TITLE
Updated dataset

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/nhanesShinyBP#16]
I added a variable to the dataset "subpophtn" - can you restrict all analyses to people with subpophtn=1? Using this approach, we will not need to restrict the population to people with valid SBP and DBP values in the app.  Also, this will restrict the analysis to people with valid data on self-reported antihypertensive medication use. This is important since the weights were recalibrated to only include people with subpophtn=1.

**Comment by bcjaeger** [comment]
Done - the app now limits all analyses to this subpopulation.
