### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/nhanesShinyBP#19]
The app looks great. I don't have any additional changes at this time. Would it be possible to deploy it to a website and I can share it with a couple of select people?

**Comment by bcjaeger** [comment]
I think so! I will try placing it onto a shiny server tomorrow and let you know how it goes.

**Comment by bcjaeger** [comment]
Done! It seems to be working: https://bcjaeger.shinyapps.io/nhanesShinyBP/
