### ISSUE TITLE
Two items

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/nhanesShinyBP#20]
Byron,

The website looks great. Can you make two changes?

1. Can you capitalize the N in "Non-Hispanic" - for whites, blacks and Asians?
2. When someone selects an exposure variable, can we allow them to select which levels to include?  This may be worth a zoom call since the real issue is that the numbers are too small when I used race/ethnicity (five levels) as the exposure but for gender (two levels) it was fine.

**Comment by bcjaeger** [comment]
Hi Paul, I agree on both counts. For 2, it should be possible to make a subsetting variable that is the same as the exposure. The app won't let you make a subsetting variable that is the same as the outcome though. It would definitely be good to discuss this. I've been second-guessing parts of the UI lately. I should open a separate issue to raise those thoughts.

**Comment by bcjaeger** [comment]
Closing this one and initiating an issue dedicated to possible ui changes
