### ISSUE TITLE
Inverse percentages/counts

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/nhanesShinyBP#21]
Some users may want to know the inverse of the statistics that we provide. For example, how many US adults have uncontrolled BP?  Should we add new variables (e.g., uncontrolled BP (SBP>=130 mm Hg or DBP >=80 mm Hg) or add a new function? I am leaning towards new variables since it may be useful to keep the interface simple.  Thoughts?

**Comment by bcjaeger** [comment]
Definitely - the UI is already on the cusp of being too complicated. Anything we can do to keep it from getting more complicated is a win. I can make the inverse of BP control and include it in the app as a separate variable - are there any other types of variables that would be good to include an inverse form for?

**Comment by bcjaeger** [comment]
Closing this for now since we have the inverse BP control outcomes. May revisit in the future if we have more possible inverse outcomes to include.
