### ISSUE TITLE
Cholesterol variables are ready!

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/nhanesShinyBP#28]
I have finished the initial coding of the lipid variables including cholesterol-lowering medications.  I would like to discuss someone double checking my code.  I can probably ask Adam Bress but let's discuss.  

I will be sending both of you a variable listing and a SAS data set.  This data set has a limited number of variables so it would be great to merge this data set with the NHANES BP data set by seqn.  

If you want, we can set up a call to discuss this.

**Comment by bcjaeger** [comment]
Nice! I'd like to discuss this as well. What day/times would work best for you? I'm open on Tuesday/Wednesday afternoon and almost all of Thursday/Friday

**Comment by bcjaeger** [comment]
@ligongus, would you like to join the discussion?

**Comment by pmuntner** [comment]
I am free Wednesday at 2pm to 3pm and 3:30pm to 5pm CT. Byron? Ligong?

**Comment by bcjaeger** [comment]
Those times work great for me. How about you @ligongus?

**Comment by ligongus** [comment]
Both times will work for me also.
