### ISSUE TITLE
eGFR

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/nhanesShinyBP#29]
Ligong,

I used the old code for eGFR. There is a 2021 formula that does not include race. Do you have access to SAS code to calculate eGFR without race?

This will need to be updated in both the BP and cholesterol data sets.

Paul

**Comment by ligongus** [comment]
Dr. Muntner,
Below are the SAS codes. Please let me know if I need to do anything else about it.

*************************Example codes for eGFR, version 2, estimated without Race************************;
****RIAGENDR = sex (1=male,2=female);
****RIDAGEYR = age in years
**** LBXSCR= serum creatinine in mg/dL;
if riagendr=2 then Kappa=lbxscr/0.7;
if riagendr=1 then Kappa=lbxscr/0.9;
term1=kappa;
if riagendr=2 then a1=-0.241;
if riagendr=1 then a1=-0.302;
a2=-1.2;
c=0.9938;
d=1;
if riagendr=2 then d=1.012;
if term1<=1 then egfr=142 *(term1**a1) * (c**ridageyr) * d; 
if term1>1  then egfr=142 *(term1**a2) * (c**ridageyr) * d;

**Comment by pmuntner** [comment]
Ligong,

Can we discuss this on Monday or Tuesday?  I will follow-up.

Thanks!

Paul

**Comment by ligongus** [comment]
I will have time on both days.

**Comment by ligongus** [comment]
I do not know why, but after I pasted the SAS codes above, the ** was missed. Below are the corrected codes;
*Example codes for eGFR, version 2, estimated without Race;
****RIAGENDR = sex (1=male,2=female);
****RIDAGEYR = age in years
**** LBXSCR= serum creatinine in mg/dL;
if riagendr=2 then Kappa=lbxscr/0.7;
if riagendr=1 then Kappa=lbxscr/0.9;
term1=kappa;
if riagendr=2 then a1=-0.241;
if riagendr=1 then a1=-0.302;
a2=-1.2;
c=0.9938;
d=1;
if riagendr=2 then d=1.012;
if term1<=1 then egfr=142 *(term1**a1) * (c**ridageyr) * d;
if term1>1 then egfr=142 *(term1**a2) * (c**ridageyr) * d;

**Comment by ligongus** [comment]
Oops. The ** missed again. The ** should be between term1 and a1 or a2, and between c and ridageyr. I put the codes below but may still not work:
*Example codes for eGFR, version 2, estimated without Race;
****RIAGENDR = sex (1=male,2=female);
****RIDAGEYR = age in years
**** LBXSCR= serum creatinine in mg/dL;
if riagendr=2 then Kappa=lbxscr/0.7;
if riagendr=1 then Kappa=lbxscr/0.9;
term1=kappa;
if riagendr=2 then a1=-0.241;
if riagendr=1 then a1=-0.302;
a2=-1.2;
c=0.9938;
d=1;
if riagendr=2 then d=1.012;
if term1<=1 then egfr=142 *(term1**a1) * (c**ridageyr) * d;
if term1>1 then egfr=142 *(term1**a2) * (c**ridageyr) * d;

**Comment by ligongus** [comment]
Please ignore the SAS codes. The ** keep being missing.

**Comment by ligongus** [comment]
OK. Thanks.

**Comment by bcjaeger** [comment]
Closing this as I think we resolved the eGFR variable (?) let me know if I'm wrong.
