### ISSUE TITLE
branding + readme

### ISSUE THREAD

**Issue by bcjaeger** [jhs-hwg/nhanesShinyBP#33]
I have two things to discuss in this issue: 

1. with the addition of cholesterol variables, our project is not specifically about blood pressure, so its name should not imply it only deals with blood pressure. and I'd like to change the name from `nhanesShinyBP` to `nhanesTrends`.
2. Hex stickers are a great way to brand projects. I made one this morning and pushed it to our readme file, which is also a new addition to the page. For convenience, I'll also put it here. FYI, the trend in the figure on the hex sticker is data from eFigure 1 in the JAMA paper (using 2017-2020 instead of 2017-2018 for the last point).

![logo](https://user-images.githubusercontent.com/11821781/181917699-80c488f4-f92d-4e32-a010-db9eee454812.png)

@pmuntner and @ligongus, what do you think of the name and the logo? This is the perfect time to make changes.

**Comment by ligongus** [comment]
Looks great! Should the name "nhanesTrends" be "NHANESTrends"?

**Comment by bcjaeger** [comment]
Thank you! =] `NHANESTrends` is more technically correct but I like making it lower case for some reason. Capital letters just read very loud to me.

**Comment by ligongus** [comment]
ok
